"""empty message

Revision ID: 1d7661b3ea5c
Revises: ce91fdb7e517
Create Date: 2023-06-08 18:52:49.605629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7661b3ea5c'
down_revision = 'ce91fdb7e517'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
