"""empty message

Revision ID: 36af52019b5b
Revises: 
Create Date: 2023-06-08 18:33:37.268384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36af52019b5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('gmail', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
