"""empty message

Revision ID: ce91fdb7e517
Revises: 36af52019b5b
Create Date: 2023-06-08 18:48:41.769585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce91fdb7e517'
down_revision = '36af52019b5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
