olap:
    target: dev
    outputs:
      dev:
        type: sqlserver
        driver: "ODBC Driver 18 for SQL Server" # (The ODBC Driver installed on your system)
        server: 10.0.10.51
        port: 1433
        database: serving_1_dbt
        schema: linh_vuc_01
        user: data_de_sa_1
        password: NNhe)TM+aMEU
        TrustServerCertificate: yes