dbt_tutorial:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server" # (The ODBC Driver installed on your system)
      server: 10.10.10.10
      port: 1433
      database: dbt_labs
      schema: test
      user: delabs
      password: H1z1@#2022
      TrustServerCertificate: yes